# Generated by Django 5.2.5 on 2025-08-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('student_id', models.CharField(max_length=11)),
                ('branch', models.CharField(max_length=21)),
            ],
        ),
    ]
